spring:
  datasource:
    url: jdbc:mariadb://eat-it.c4llgditmke8.ap-northeast-2.rds.amazonaws.com:3306/eat_it
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: npRAkO6jFTPC9x5kXQZk

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
